name: 'RPM Build'
description: 'Build RPMs from spec file'
author: 'Mikko Partio'

inputs: 
  spec_file:
    description: 'path to the spec file'
    required: true
    default: '*.spec'                     #Any spec file in top 
  additional_repositories:
    description: 'A list of additional repositories to install'
    required: false
  enable_repositories:
    description: 'A list of additional repositories to enable'
    required: false
  enable_modules:
    description: 'A list of dnf modules to enable'
    required: false
  disable_modules:
    description: 'A list of dnf modules to disable'
    required: false
  dnf_commands:
    description: 'Additional dnf commands to run'
    required: false
outputs:
  srpm_dir_path:
    description: 'path to SRPMS directory'
    value: ${{ steps.build_rpm.outputs.srpm_dir_path }}
  rpm_dir_path:
    description: 'path to RPMS directory'
    value: ${{ steps.build_rpm.outputs.rpm_dir_path }}

runs:
  using: 'composite'
  steps:
    - run: echo Building spec ${{ inputs.spec_file }}
      shell: bash
    - run: sh ${GITHUB_ACTION_PATH}/entrypoint.sh "${{ inputs.spec_file }}" "${{ inputs.additional_repositories }}" "${{ inputs.enable_repositories }}" "${{ inputs.enable_modules }}" "${{ inputs.disable_modules }}" "${{ inputs.dnf_commands }}"
      shell: bash
      id: build_rpm

branding:
  icon: 'package'
  color: 'red'
